### ISSUE TITLE
Update internal documentation references to Federalist

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist-team#27]
#### User Story

Internal documentation that references Federalist is out of date, as a BD and 18F staff, they require information to match public sources.

 #### Background info

Are we aware of how BD and strategy teams obtain their Federalist information? Is there ONE slide deck that is used across the organization to talk about 18F products and services? 

#### Acceptance Criteria

- [ ] Slides (internal Federalist team)
- [ ] Slides (external 18F) 
- [ ] BD drive (https://drive.google.com/drive/u/0/folders/0BxS2K9tCtwSXYks4anNXNlowcTA)

**Comment by amirahaziz** [comment]
Going through the 18F BD drive, I created a spreadsheet with everything inside that may need updating/refreshing. I think once this is cleaned up, we should use it at the TTS level to circulate what Federalist is, and how we should be talking about it to our customers: https://docs.google.com/spreadsheets/d/1p11HhnAXp07abJm57n76IIENMmfnYJGd7m5UYLVHzOA/edit#gid=0

**Comment by Bryanthales-zz** [comment]
Update this documentation, which is frequently used by Kenny when discussing external.

**Comment by davemcorwin** [comment]
This repo was archived and is not generally used so closing this issue, @eddietejeda please transfer is needed
