### ISSUE TITLE
Review with Eddie materials for 1.23 18F team coffee 

### ISSUE THREAD

**Issue by amirahaziz** [18F/federalist-team#7]
Current slide:

Moved it to the cloud.gov P&L, moved Eddie and Amir onto it full-time. It’s now projected to recover its costs and more thanks to Eddie’s stewardship.

Additional language:
- Why the merge, where did this decision come from
- What has come out of it 
- What to look forward to in the future

**Comment by eddietejeda** [comment]
hey @eddietejeda can you fwd presentation to Amirah?
